### PR TITLE
Add clamav to Gemfile

### PR DESCRIPTION
**Pull request by straccers**
I have added the clamav gem into the Gemfile

### CODE REVIEW

**Comment by yf508** [comment]
@straccers please run bundle install and commit Gemfile.lock as well to pass travis test.

**Comment by straccers** [comment]
Bundle install will only actually run succesfully once the clamav and
libclamav-dev packages have been installed on the server. Will  just giving
it an existing gemfile lock from another machine be sufficient for it to
pass the travis test?






Regards
Peri Stracchino
University of York Digital Library Technical Team

**Comment by yf508** [comment]
Good point, then update .travis.yml as well to install dependencies.

**Comment by straccers** [comment]
OK I'v installed the clamav libraries on my vagrant and then rebuilt the
Gemfile lock which is now in the add-clamav branch . I suggest we make the
changes to travis together, as I have not worked with travis yet



Regards
Peri Stracchino
University of York Digital Library Technical Team

**Pull request merged**
