### PR TITLE
Issue 44 changes to download survey

### PR DESCRIPTION
**Pull request by straccers**
updated survey test and dropdown list for countries, populated from authorities

### CODE REVIEW

**Comment by yf508** [comment]
1) don't think country will be saved to Downloader model because both input & select have the same name , e.g. 'summary[participants_country][]'. Did you test if the controller works? 
2) Remove '=' in the following:
  <%=countries.each do |terms| %>
            <%=terms[1].each do |t| %>
3) The above 2 loops can be simplified to:
<% countries["terms"].each do |t| %>
4) Pls follow bootstrap conventions, e.g. add 'col-sm-3' class to label element and add 'col-sm-9' to select element. The current styles may cause inconsistent/messy UI in some devices.

**Comment by paluchas** [comment]
I have improved code quality as suggested.

**Comment by yf508** [comment]
Thanks, we don't need this line at all:

<input name="survey[participants_country][]" type="hidden" value="value">

**Comment by straccers** [comment]
Hi Frank

Re testing the controller - I completed the survey and submitted it, it
reported success but I dont know how accurate a measure of succss this is.
What other tests do you recommend? One issue is that having once completed
the survey it wont offer me another - presumably there is some cookie or
something I might need to clear?


Regards
Peri Stracchino
University of York Digital Library Technical Team

**Pull request merged**
