### PR TITLE
Issue 257 set pdf to download

### PR DESCRIPTION
**Pull request by yf508**
Fixed issue 257:
1) if multiple files being uploaded, make sure the first file is PDF if exists
2) allow users to change thumbnail/representative media via file manager

### CODE REVIEW

**Comment by paluchas** [comment]
@yf508 Thumbnails are still not generated during upload to dev.*. It looks like we have some permission issue access issue.

```
E, [2019-01-02T15:59:05.934327 #4104] ERROR -- : [ActiveJob] [CreateDerivativesJob] [6f4aeef1-4a29-42a5-82d9-8b81e7be240c] Error performing CreateDerivativesJob (Job ID: 6f4aeef1-4a29-42a5-82d9-8b81e7be240c) from Async(ingest_queue) in 738.4ms: MiniMagick::Invalid (`identify /tmp/mini_magick20190102-4104-1etse63.pdf` failed with error:
identify: not authorized `/tmp/mini_magick20190102-4104-1etse63.pdf' @ error/constitute.c/ReadImage/41
```

@Jimadine do you think we need to change a policy on our Ubuntu servers re ImageMagic access to PDF files as mentioned [here](https://github.com/minimagick/minimagick/issues/473)?

**Comment by paluchas** [comment]
Just to commented that the last successful PDF thumbnails where generated before our work on 7th September 2018.

@yf508 Do you have some ideas how we can regenerate those missing thumbnails once ImageMagic is configured correctly?

**Comment by yf508** [comment]
@paluchas possibly this [hyrax job](https://github.com/samvera/hyrax/blob/master/app/jobs/create_derivatives_job.rb) can do it:

**Comment by Jimadine** [comment]
@paluchas According to [https://www.kb.cert.org/vuls/id/332928/](https://www.kb.cert.org/vuls/id/332928/):

> This issue is addressed in Ghostscript version 9.24

All our VMs that have ImageMagick installed have Ghostscript 9.26, so are covered. However, the above page does go on to say that the other workarounds are advisable too. As it sounds like we absolutely need PDF generation to work, but not the other ghostscript format types, perhaps the following ImageMagick policy file excerpt would be preferable:

```
<!-- disable ghostscript format types, bar PDF -->
<policy domain="coder" rights="none" pattern="EPI" />
<policy domain="coder" rights="none" pattern="EPS" />
<policy domain="coder" rights="read | write" pattern="PDF" />
<policy domain="coder" rights="none" pattern="PS" />
<policy domain="coder" rights="none" pattern="XPS" /> 
```
Let me know your thoughts.

**Comment by paluchas** [comment]
@yf508 @Jimadine  I'll merge this as this is more emergency issue. Puppet will be solved independently.

**Comment by Jimadine** [comment]
@paluchas @yf508 I've made changes to _dlib_tools_ puppet code to manage ImageMagick's policy.xml ( see git refs feba924 & d67b969 ). This is set up on dlibingdev0. If you're happy with this, please let me know and I'll set this up on our other VMs.

**Pull request merged**
