### PR TITLE
Feature/help page ux

### PR DESCRIPTION
**Pull request by paluchas**
- Load TinyMCE configuration
- Use JQuery Accordion at help page

### CODE REVIEW

**Comment by yf508** [comment]
@paluchas Do you have to upgrade tinymce-rails in this PR? This PR seems upgrading other gems including nokogiri which I've added in my branch. If it's avoidable, we can do all upgrades together to make it simpler. If not, we will leave the conflicts to solve later.

**Comment by paluchas** [comment]
@yf508 I'll force removed Gemfile.lock update with TinyMCE update

**Comment by paluchas** [comment]
@yf508 this is ready now. Can you merge it and rebase onto Hyrax upgrade branch, please?

**Review by yf508 — APPROVED** [review]
Sounds good to me.

**Pull request merged**
